let equipo;
let nombreDuenio;
let plataDuenio;
let nombre;
let edad;
let posicion;
let partidos;
let promedio;
let sueldo;
let infracciones;
let arqueros = 0;
let defensores = 0;
let volantes = 0;
let delanteros = 0;
let sueldoTotal = parseInt(0);
let sueldoDisponible = parseInt(0);
let contador = 0;
let cumpleCantJugadores;
let elMasVeterano;
let nombreClub;
let id = 1;
const jugadores = [];
const ingresantes = [];
let innerListado = "";